### ISSUE TITLE
Module parameters

### ISSUE THREAD

**Issue by sissbruecker** [amadare42/typesafe-container#2]
First, thanks for building this! I saw something like this in an [SO post](https://stackoverflow.com/questions/51176441/how-to-declare-generic-mapped-types-for-this-dependency-injection-container-in) and really liked the approach. Your library is basically a complete solution for this approach with modules and different lifecycles.

One thing that I was thinking about was how to provide a parameter to a module. It is possible to override the constructor, but it seems like that requires quite a bit of typing - this is basically what you do in the loggable module example. Another approach that I thought of was to add a setter function to the module that returns `this`. Basically:
```
class NextContextModule extends BaseModule {
  ctx: AppContext

  setContext(ctx: AppContext) {
    this.ctx = ctx
    return this
  }
}
```
and then register it with:
```
  const builder = new ContainerBuilder()
    .register(r => new NextContextModule(r).setContext(ctx))
```

Less code, but one could forget to call the setter. Can you think of other solutions?

Thanks and regards, Sascha

**Comment by amadare42** [comment]
Hello, Sascha. Thanks for your interest!

Could you please come up with some use-case where this is useful? I used this library for some simple services and never needed to do this. All environment and DB configs, for example, were just in the Config module. So I didn't have to configure modules behavior on registration.

As for putting additional dependencies to the module object, it can be kinda dangerous right now. On container registration, exactly one field will be omitted: `register`. So if you add some private fields to the class, all of them will be added as a dependency to the resulting container even if typings will not represent that.

Currently, I see only one safe way to do this - you can just capture your values as closure and have a bit hacky, but reliable solution:
```typescript
// declaration
type Dependencies = Foo | Bar;
function moduleA(r: ModuleRegistrar<Dependencies>, value: number) {
    return new class ModuleA extends BaseModule<Dependencies> {
        constructor(r: ModuleRegistrar<Dependencies>) {
            super(r);
        }
        value = this.register.singleton(ctr => value + 1);        
    }(r);
}

// registration
builder.register(r => moduleA(r, 41))
```

P.S. There is a problem with dependencies that are located in the same module. It will be fixed soon, but it will probably require some minor breaking changes in the api.

**Comment by sissbruecker** [comment]
Yes, having a module factory function is another option, but that also requires writing out somewhat elaborate typings. No big deal though 👍

Our use-case is around a React application with server-side rendering which loads some initial data for each page requested. Because the data loaded is user-specific, we had to provide the cookies from the page request to the service that loads the user-specific data. That meant that we needed to create a new (user-specific) container for each page request and provide the cookies (among other stuff) as a parameter to the container or its modules.

In the end we didn't go with a IOC container, it would have been to much for our current use case. For now we just hook up the few dependencies that we have manually and provide those as a simple "service locator object" to the rest of the application. But I hope your project picks up some more interest, I think it's a rather clever solution for a simple type-safe container.

**Comment by amadare42** [comment]
Thanks for your feedback.

After some consideration, I think that indeed, for some cases it is easier sometimes to pass some state from outside of a module. So I implemented this as a feature. I'll link paragraph about it just it case :)
[06. Stateful Module](https://github.com/amadare42/typesafe-container#06-stateful-module).

Good luck with your projects.

**Comment by sissbruecker** [comment]
Looks good! 👍
